apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: orangesys.app.orangesys.io
spec:
  group: app.orangesys.io
  names:
    kind: Orangesys
    listKind: OrangesysList
    plural: orangesys
    singular: orangesys
  scope: Namespaced
  version: v1alpha1
